const $=id=>document.getElementById(id),msg=s=>{$("status").textContent=s;setTimeout(()=>$("status").textContent="",2800)};let profiles=[],routes=[],groups=[],history=[];
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
const keys=["from","to","date","class","qty","train"];
async function data(){return await chrome.storage.local.get(["profiles","routes","groups","history","search","dark","lang","checks","reminder","pin"])}
async function load(){const x=await data();profiles=x.profiles||[];routes=x.routes||[];groups=x.groups||[];history=x.history||[];const s=x.search||{};keys.forEach(k=>{if(s[k]!=null)$(k).value=s[k]});render();document.querySelectorAll(".check").forEach((c,i)=>{c.checked=!!(x.checks||[])[i];c.onchange=saveChecks});if(x.dark)document.body.classList.add("dark");$("reminder").value=x.reminder||""}
function render(){ $("profile").innerHTML=profiles.length?profiles.map((p,i)=>'<option value="'+i+'">'+esc(p.name||("Passenger "+(i+1)))+"</option>").join(""):'<option value="">No profiles</option>'; $("list").innerHTML=profiles.map((p,i)=>'<div><span>'+esc(p.name)+" • "+esc(p.phone||"no phone")+'</span><button data-d="'+i+'">Delete</button></div>').join("");document.querySelectorAll("[data-d]").forEach(b=>b.onclick=async()=>{profiles.splice(+b.dataset.d,1);await chrome.storage.local.set({profiles});render()});$("route").innerHTML='<option value="">Saved routes</option>'+routes.map((r,i)=>'<option value="'+i+'">'+esc(r.name||((r.from||"?")+" → "+(r.to||"?")))+"</option>").join("");$("group").innerHTML='<option value="">Family groups</option>'+groups.map((g,i)=>'<option value="'+i+'">'+esc(g.name)+" ("+g.members.length+")</option>").join("");$("stats").innerHTML='<div class="stat"><b>'+profiles.length+'</b>Passengers</div><div class="stat"><b>'+routes.length+'</b>Routes</div><div class="stat"><b>'+history.length+'</b>Journeys</div>';$("history").innerHTML=history.slice(-5).reverse().map((h,i)=>'<div class="history"><button data-h="'+(history.length-1-i)+'">×</button><b>'+esc(h.from)+" → "+esc(h.to)+'</b><br><small>'+esc(h.date)+" • "+esc(h.note||"No note")+'</small></div>').join("");document.querySelectorAll("[data-h]").forEach(b=>b.onclick=async()=>{history.splice(+b.dataset.h,1);await chrome.storage.local.set({history});render()});updateProgress()}
async function saveChecks(){await chrome.storage.local.set({checks:[...document.querySelectorAll(".check")].map(c=>c.checked)});updateProgress()}function updateProgress(){const c=[...document.querySelectorAll(".check")];$("progress").textContent=c.filter(x=>x.checked).length+"/"+c.length}
function currentSearch(){return Object.fromEntries(keys.map(k=>[k,$(k).value]))}
async function send(type,data){const ts=await chrome.tabs.query({active:true,currentWindow:true});if(!ts[0]?.id)return msg("Open the Railway site first");chrome.tabs.sendMessage(ts[0].id,{type,data},r=>{if(chrome.runtime.lastError)msg("Open the official Railway page first");else if(r?.message)msg(r.message);else msg("Done")})}
$("add").onclick=async()=>{let name=prompt("Profile name");if(!name)return;profiles.push({name,fullName:prompt("Full name")||"",phone:prompt("Mobile")||"",nid:prompt("NID")||"",passport:prompt("Passport")||"",note:prompt("Note (optional)")||""});await chrome.storage.local.set({profiles});render();msg("Passenger saved")};
$("edit").onclick=async()=>{let i=+$("profile").value,p=profiles[i];if(!p)return msg("Select a passenger");p.name=prompt("Profile name",p.name)||p.name;p.fullName=prompt("Full name",p.fullName)||"";p.phone=prompt("Mobile",p.phone)||"";p.nid=prompt("NID",p.nid)||"";p.passport=prompt("Passport",p.passport)||"";await chrome.storage.local.set({profiles});render();msg("Passenger updated")};
$("fill").onclick=()=>send("fillProfile",profiles[+$("profile").value]);
$("fillGroup").onclick=()=>{let g=groups[+$("group").value];if(!g)return msg("Select a group");send("fillProfiles",g.members.map(i=>profiles[i]).filter(Boolean))};
$("saveGroup").onclick=async()=>{let name=$("groupName").value.trim()||prompt("Family/group name");if(!name)return;let members=profiles.map((_,i)=>i);groups.push({name,members});await chrome.storage.local.set({groups});$("groupName").value="";render();msg("Group saved with all current profiles")};
$("saveSearch").onclick=async()=>{let r={name:prompt("Route name")||(( $("from").value||"?")+" → "+($("to").value||"?")), ...currentSearch()};routes.push(r);await chrome.storage.local.set({routes,search:r});render();msg("Route saved")};
$("route").onchange=()=>{let r=routes[+$("route").value];if(r)keys.forEach(k=>$(k).value=r[k]||"")};
$("repeat").onclick=()=>{let h=history[history.length-1];if(!h)return msg("No saved journey");keys.forEach(k=>$(k).value=h[k]||"");send("fillSearch",currentSearch())};
$("delRoute").onclick=async()=>{let i=+$("route").value;if(routes[i]){routes.splice(i,1);await chrome.storage.local.set({routes});render();msg("Route deleted")}};
$("fillSearch").onclick=()=>send("fillSearch",currentSearch());
$("checkForm").onclick=()=>send("checkForm");
$("clear").onclick=()=>send("clear");
$("open").onclick=()=>chrome.tabs.create({url:"https://eticket.railway.gov.bd/"});
$("theme").onclick=async()=>{document.body.classList.toggle("dark");await chrome.storage.local.set({dark:document.body.classList.contains("dark")})};
$("lang").onclick=async()=>{let x=await data();await chrome.storage.local.set({lang:x.lang==="bn"?"en":"bn"});$("lang").textContent=x.lang==="bn"?"বাংলা":"English"};
$("export").onclick=async()=>{let x=await data();delete x.pin;let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(x,null,2)],{type:"application/json"}));a.download="railway-assistant-backup.json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$("import").onchange=e=>{let f=e.target.files[0];if(!f)return;let rr=new FileReader();rr.onload=async()=>{try{let x=JSON.parse(rr.result);await chrome.storage.local.set({profiles:x.profiles||[],routes:x.routes||[],groups:x.groups||[],history:x.history||[],search:x.search||{}});await load();msg("Backup imported")}catch{msg("Invalid backup")}};rr.readAsText(f)};
$("setReminder").onclick=async()=>{let v=$("reminder").value;if(!v)return msg("Select time");let when=new Date(v).getTime();if(when<=Date.now())return msg("Choose a future time");await chrome.alarms.create("railway-reminder",{when});await chrome.storage.local.set({reminder:v});msg("Reminder set")};
$("clearReminder").onclick=async()=>{await chrome.alarms.clear("railway-reminder");await chrome.storage.local.remove("reminder");$("reminder").value="";msg("Reminder cleared")};
$("saveHistory").onclick=async()=>{let s=currentSearch();history.push({...s,note:$("historyNote").value,createdAt:new Date().toISOString()});await chrome.storage.local.set({history});$("historyNote").value="";render();msg("Journey saved")};
$("wipe").onclick=async()=>{if(confirm("Delete all Railway Assistant local data?")){await chrome.storage.local.clear();await chrome.alarms.clearAll();location.reload()}};
$("pinSave").onclick=async()=>{let p=$("pin").value;if(p.length<4)return msg("PIN must be at least 4 digits");await chrome.storage.local.set({pin:p});$("pin").value="";unlock();msg("PIN saved")};
$("pinUnlock").onclick=async()=>{let x=await data();if(!x.pin)return unlock();if($("pin").value===x.pin){$("pin").value="";unlock()}else msg("Wrong PIN")};
function unlock(){$("lockBox").classList.add("hidden");$("app").classList.remove("hidden");load()}
(async()=>{let x=await data();if(!x.pin)unlock();else $("pinHint").textContent="Enter your PIN to unlock saved data."})();