const $=id=>document.getElementById(id),msg=s=>{$("status").textContent=s;setTimeout(()=>{$("status").textContent=""},2500)};let profiles=[];
async function load(){let x=await chrome.storage.local.get(["profiles","search","dark"]);profiles=x.profiles||[];let s=x.search||{};["from","to","date","class","qty"].forEach(k=>{if(s[k]!=null)$(k).value=s[k]});$("profile").innerHTML=profiles.length?profiles.map((p,i)=>'<option value="'+i+'">'+esc(p.name||"Passenger "+(i+1))+"</option>").join(""):'<option value="">No profiles</option>';$("list").innerHTML=profiles.map((p,i)=>'<div><span>'+esc(p.name||("Passenger "+(i+1)))+'</span><button data-d="'+i+'">Delete</button></div>').join("");document.querySelectorAll("[data-d]").forEach(b=>b.onclick=async()=>{profiles.splice(+b.dataset.d,1);await chrome.storage.local.set({profiles});load()});if(x.dark)document.body.classList.add("dark")}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
$("add").onclick=async()=>{let name=prompt("Profile name");if(!name)return;let p={name,fullName:prompt("Full name (optional)")||"",phone:prompt("Mobile (optional)")||"",nid:prompt("NID (optional)")||"",passport:prompt("Passport (optional)")||""};profiles.push(p);await chrome.storage.local.set({profiles});load();msg("Profile saved")};
$("fill").onclick=()=>{let p=profiles[+$("profile").value];if(!p)return msg("Select a profile");chrome.tabs.query({active:true,currentWindow:true},ts=>chrome.tabs.sendMessage(ts[0].id,{type:"fillProfile",profile:p},()=>msg(chrome.runtime.lastError?"Open the Railway site first":"Profile filled")))}; 
$("clear").onclick=()=>chrome.tabs.query({active:true,currentWindow:true},ts=>chrome.tabs.sendMessage(ts[0].id,{type:"clear"},()=>msg(chrome.runtime.lastError?"Open the Railway site first":"Editable fields cleared")));
$("fillSearch").onclick=()=>chrome.tabs.query({active:true,currentWindow:true},ts=>chrome.tabs.sendMessage(ts[0].id,{type:"fillSearch",data:Object.fromEntries(["from","to","date","class","qty"].map(k=>[k,$(k).value]))},()=>msg(chrome.runtime.lastError?"Open the Railway site first":"Search fields filled")));
$("saveSearch").onclick=async()=>{await chrome.storage.local.set({search:Object.fromEntries(["from","to","date","class","qty"].map(k=>[k,$(k).value]))});msg("Search saved")};
$("open").onclick=()=>chrome.tabs.create({url:"https://eticket.railway.gov.bd/"});
$("theme").onclick=async()=>{document.body.classList.toggle("dark");await chrome.storage.local.set({dark:document.body.classList.contains("dark")})};
$("export").onclick=async()=>{let blob=new Blob([JSON.stringify(profiles,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="railway-profiles.json";a.click();URL.revokeObjectURL(a.href)};
$("import").onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=async()=>{try{let x=JSON.parse(r.result);if(!Array.isArray(x))throw 0;profiles=x;await chrome.storage.local.set({profiles});load();msg("Profiles imported")}catch{msg("Invalid JSON file")}};r.readAsText(f)};
load();